
[book]
title = "Documentation"
authors = ["Patrick Kilisio"]
description = "Documentation of what i learn on a daily basis."

[build]
build-dir = "book"
create-missing = true
preprocess = ["links", "index"]

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true

